---
development:
  cloud_name: dzy6tpyc7
  api_key: '636881875412737'
  api_secret: W4TZ4x1EfeBC2v_etEDQ3OL1B_M
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dzy6tpyc7
  api_key: '636881875412737'
  api_secret: W4TZ4x1EfeBC2v_etEDQ3OL1B_M
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dzy6tpyc7
  api_key: '636881875412737'
  api_secret: W4TZ4x1EfeBC2v_etEDQ3OL1B_M
  enhance_image_tag: true
  static_file_support: false
